### ISSUE TITLE
not present in maven central

### ISSUE THREAD

**Issue by ghost** [Almeros/android-gesture-detectors#12]
Is it possible to upload them in maven central please?

**Comment by AndroidDeveloperLB** [comment]
How should it be in the "build.gradle" file then?

**Comment by agap** [comment]
@AndroidDeveloperLB compile 'com.ryanharter.android-gesture-detectors:library:0.0.1'

**Comment by devemux86** [comment]
Is it actually the same?

I tried 0.0.4 and it crashed on some gestures (I haven't kept the exceptions).

**Comment by AndroidDeveloperLB** [comment]
@agap Doesn't work. It says :

Error:(26, 13) Failed to resolve: com.ryanharter.android-gesture-detectors:library:0.0.1
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by agap** [comment]
@AndroidDeveloperLB make sure that     
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
and
mavenCentral()
both are in your repositories' list.

**Comment by AndroidDeveloperLB** [comment]
@agap I'm not sure where exactly should I put those.
Is it somewhere here:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

?

**Comment by agap** [comment]
@AndroidDeveloperLB that's the content of the top-level build file; you should have `build.gradle` file inside your application/library module. in this build file find a top-level closure called `repositories` (or create one if it doesn't exist) and make sure it looks like this:

    repositories {
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
You can have other repos here, just make sure you included sonatype. After that you can try to build again.
Note: and I was wrong, looks like 0.0.1 isn't the latest version. :)

**Comment by AndroidDeveloperLB** [comment]
@agap So which is the correct version?
I've tried adding those lines to the "android" part, but now I get this error:

    Error:Execution failed for task ':app:processDebugManifest'.
    > Manifest merger failed with multiple errors, see logs

and if I got up a few lines, I see this:

    Error:(5, 5) Attribute application@icon value=(@drawable/ic_launcher) from AndroidManifest.xml:5:5
    Error:(6, 5) Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:6:5

As if there was a collision of resources that it couldn't handle...
Am I correct?

Would it help if I tell you which project I'm trying this on?
If so, here it is:
https://github.com/AndroidDeveloperLB/MultiTouchPlaceholderView

**Comment by jitpack-io** [comment]
Btw, you can also download it from: https://jitpack.io/#Almeros/android-gesture-detectors/1ffb8444ee

Using the commit id '1ffb8444ee' here. Would be nice to have a GitHub release though so that we can use a version.

**Comment by sengsational** [comment]
The com.ryanharter  0.0.4 (https://mvnrepository.com/artifact/com.ryanharter.android-gesture-detectors/library/0.0.4) is NOT the same code as the code here; it bombs with NPE on touch events.

There are only 5 classes, so you can just do a text copy / paste and you'll know what you're getting, as opposed to accepting some random code in your project.

**Comment by rharter** [comment]
I second what @sengsational says. This old builds were based on this, but I don't maintain them anymore. We recently got some new management on this project so I'd recommend using the code here.

**Comment by Almeros** [comment]
I updated the project to make use of Jitpack.io. Please see the README.md for more information. I hope this is working for you all. Now closing this issue.
