### ISSUE TITLE
BSD 2-clause license?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Almeros/android-gesture-detectors#14]
I'm not sure what it means. Can anyone please help with this?
I've found this one:
https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)

As English isn't my main language, I couldn't understand its meaning, even though I've read in multiple websites (including Wikipedia).
1. What does "Hold Liable" mean? that the original creator of the library won't be charged for damages? 
2. What does " Include Copyright" mean? that the app must show the description of the license somewhere within (like the "about" screen or something) ? or just the code should have it ?
   If just the code, what's the difference between it and Apache2 license ?

3.What about derivatives? What if I wish to fork the library? should it also be BSD 2-clause licensed ?

What should and what shouldn't I do?

**Comment by jeffdav** [comment]
The license is include in the root of this repository:
https://github.com/Almeros/android-gesture-detectors/blob/master/LICENSE.md

**Comment by AndroidDeveloperLB** [comment]
I don't understand what this means. That if I use this, I have to show this license somewhere? In code? At runtime? On "about" page at runtime?

**Comment by AeroEchelon** [comment]
For those still wondering about this license; TL;DR has a great resource on this:

**BSD 2-clause license**
https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)

**Comment by AndroidDeveloperLB** [comment]
@AeroEchelon So it says :
" Include Copyright - Describes whether the original copyright must be retained."
What does it mean? How do you retain a copyright, if it's ok to copy the code?

"Include License - Including the full text of license in modified software."
Where to include the license? In code? at runtime? On "About" page at runtime?

**Comment by Almeros** [comment]
"Hold Liable" means you can't sue me or anyone else that helps building this framework if something goes wrong while using this framework.

Next to this it would be nice to credit (on an about page) the people who worked on this framework if you use it in your project. 
If you fork the project and change it, you must keep the BSD licence as it is right now in the fork.

_The above is for explanatory reasons. The BSD licence is always leading!_

**Comment by AndroidDeveloperLB** [comment]
So it's perfectly ok to use the code or a part of it, modify it, without me worrying of someone suing me for doing so?
What do you mean "The BSD licence is always leading" ? Leading what?

**Comment by Almeros** [comment]
Yes, I will not sue you, but be kind and tell your app users you used this framework and where to find it.

With my last italic sentence I'm saying my comments are just informative and what is in the BSD license text is what should be interpreted by lawyers and legal stuff people... May it ever come to such thing...
Which will never be so (I hope!)

**Comment by Almeros** [comment]
I'm not an expert on this subject. I added the BSD licence so people could use it as freely as possible but with giving credits to who deserves the credits, and... so I can't get sued.

Not to be rude, but please look up your legal questions about BSD on Google... and start coding and have fun ;)

**Comment by AndroidDeveloperLB** [comment]
Thank you
