### ISSUE TITLE
Rotate only and do not Scale and Scale only and do not rotate

### ISSUE THREAD

**Issue by fahimsakri** [Almeros/android-gesture-detectors#18]
How can i achieve that  if the rotate event is currently active then scale should not happen and when scale event is currently active then rotate should not happen?

**Comment by Almeros** [comment]
You could/should use a flag in your activity which you can set to a certain state (i.e. rotating or scaling)  from within your eventhandler and test for a flag state in the other eventhandler preventing it from handling if another state is currently active...
