### ISSUE TITLE
cant compile with gradle

### ISSUE THREAD

**Issue by Watsonibm** [Almeros/android-gesture-detectors#21]
Hello,

I use: compile 'com.almeros.android-gesture-detectors:library:1.0' in gradle and get "failed to resolve"

can you please help me fix that?

Thank you

**Comment by jeffdav** [comment]
I pasted in `compile 'com.almeros.android-gesture-detectors:library:1.0'` as well and I get "Could not find com.almeros.android-gesture-detectors:library:1.0."  Latest Android Studio 1.4.

**Comment by medonja** [comment]
In Maven central there seems to exist the com.ryanharter.android-gesture-detectors:library:0.0.4 artifact. Looks like the latest release, though I haven't verified that.

**Comment by ThoastProductions** [comment]
Having the same problem. What is the url to the repo? 
This works for other projects:
`allprojects {
    repositories {
        jcenter()
        maven { url "repo url" }
    }
}`

**Comment by Caspain** [comment]
android studio failed mainly because that build cannot compiled reason being it does not exist.
try this version: compile 'com.ryanharter.android-gesture-detectors:library:0.0.4'

**Comment by Almeros** [comment]
I updated the project to make use of Jitpack.io for Gradle dependencies. Hope this helps you. Now closing this issue.
