### ISSUE TITLE
Two-finger pinch-zoom about the center of the two pointers

### ISSUE THREAD

**Issue by TedJackson** [Almeros/android-gesture-detectors#24]
This gesture detector example is very helpful, but it appears to always zoom relative to the center of the image, which may be well outside the currently displayed area.  Would it be possible to zoom about the center of the two touch positions instead?  If so, how?  Thanks.

**Comment by Almeros** [comment]
This library is not much more than a framework for you to fill in. The actual magic of how to respond to the gestures is totally up to you. What you want is totally possible using the framework, but you should do the math yourself. Please read http://code.almeros.com/android-multitouch-gesture-detectors#more-388 to get more explanation.
