### ISSUE TITLE
Handle imageView without matrix technic

### ISSUE THREAD

**Issue by dupuisdavid** [Almeros/android-gesture-detectors#26]
Hello,

I would like to use this library and handle and resize, rotate, and scale multiple imageviews but without matrix technic. Instead, I would like to user setX, setY, setRotation for example.
Problem is that I'm unable to combine the gestures together.
Do you have an example for this case ?
Thanks

David

**Comment by Almeros** [comment]
Please read http://code.almeros.com/android-multitouch-gesture-detectors#more-388

At the bottom you will read how to combine them.
