### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by zugaldia** [Almeros/android-gesture-detectors#27]
Hey @Almeros, thanks for your work here, we're big fans of this library and we use it extensively as part of our SDK https://github.com/mapbox/mapbox-gl-native. I'd love to chat with you about a few ideas we have for the project. Any chance, you can drop me a line to antonio@mapbox.com?

Thanks and cc'ing @rharter whom I've also been in touch with.

(Feel free to close this ticket, I just didn't know the best way to reach out.)

**Comment by Almeros** [comment]
Hi Antonio, great to hear you like it and that the lib is (still) useful to you! I added you as a collaborator to the github library.
