### ISSUE TITLE
View shake when touch 

### ISSUE THREAD

**Issue by LionelCursor** [Almeros/android-gesture-detectors#8]
when use in a view which not fixed in Screen, it always tremble.

I use this:
      imageView.setRotation(deltaDegree);

**Comment by yazeed44** [comment]
i have the same problem

**Comment by yazeed44** [comment]
is it because of image view being inside layout ?

note : the same thing happens with MoveDetector

**Comment by LionelCursor** [comment]
The view I use is a custom TextView. it's trembling when rotated but not when moved.

**Comment by yazeed44** [comment]
so there's no problem with moving the view ?

if there's no problem please attach the code

**Comment by LionelCursor** [comment]
MoveListener is at last of [this file](https://github.com/LionelCursor/MoFa/blob/master/app/src/main/java/com/unique/mofaforhackday/view/MoFaTextView.java). And you can trace this inner class to find how I write. Hope to help you.

**Comment by yazeed44** [comment]
Thank you very much

**Comment by Almeros** [comment]
Looks like you guys solved it! Closing the issue now.
